# @package _global_
model:
  hidden_size: 50
  num_layer: 1
  hr_size: 30
  dropout_rate: 0.1
  fc_hidden_size: 25

  optimizer:
    optimizer_cls: 'adam'
    learning_rate: 0.001
    weight_decay: 0.0
    lr_scheduler: False
    #scheduler
    lr_scheduler_cls: 'ExponentialLR'
    gamma: 0.99

checkpoint:
  monitor: 'val_loss'

exp:
  exp_name: '3.12-mimic-ha_rnn_min'
  max_epochs: 12                   # Number of epochs
  batch_size: 32                   # Batch size
  load_pretrained: False           # Load pretrained model
  resume_train: False             # Resume training
  run_id: 0                       # Run ID of the checkpoint
  exp_id: 0                        # Experiment ID of the checkpoint