exp:
  seed: 100                         # Random seed for all the initialisations, dataset generation etc.
  accelerator: 'gpu'                         
  max_epochs_nuisance: 15                  # Number of epochs
  max_epochs_de: 10
  logging: True                     # Logging to MlFlow
  mlflow_uri: http://127.0.0.1:3333 
  batch_size: 32
  num_workers: 2
  log_every_n_steps: 100
  gradient_clip_val: 0.0
  exp_name: 'two-step-dblopt-1.0'                    #'two-step-training'

checkpoint:
  save: True
  top_k: 1
  monitor_nuisance: 'val_loss'
  monitor_de: 'val_loss_param'

defaults:
  - _self_
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog