_target_: src.data.linear_synthetic.linearMarkovianDataPipeline
n_units: 2000
n_periods: 3
sequence_length: 10
n_x: 50
n_treatments: 1
n_treatments_disc: 0
n_treatments_cont: 1
s_x: 50
s_t: 1
sigma_x: 0.5
sigma_t: 0.5
sigma_y: 1.0
gamma: 0.2
autoreg: 0.25
state_effect: 0.25
hetero_strength: 0.5
hetero_inds: []
conf_str: 5
seed: 2024
split:
  val: 0.15
  test: 0.15


