# @package _global_
dataset:
  seed: 2025
  name: mimic3_synthetic
  path: 'C:\Users\mhr_k\Data\mimic_extract\all_hourly_data_1000.h5'                  # Path with MIMIC-3 dataset (HDFStore)
  min_seq_length: 30                                        # Min sequence length in cohort
  max_seq_length: 50                                       # Max sequence length in cohort
  max_number: 10                                          # Maximum number of patients in cohort
  data_seed: 2025
  n_periods: 3                                   # Range of tau-step-ahead prediction (tau = projection_horizon + 1)
  n_treatments_seq: 1                                      # Number of random treatments trajectories, sampled for each patient
  split:
    val: 0.2
    test: 0.2
  val_batch_size: 512                                      # Batch size for evaluation
  parallel: False

  autoregressive: True

  vital_list:
    - heart rate
    - red blood cell count
    - sodium
    - mean blood pressure
    - systemic vascular resistance
    - glucose
    - chloride urine
    - glascow coma scale total
    - hematocrit
    - positive end-expiratory pressure set
    - respiratory rate
    - prothrombin time pt
    - cholesterol
    - hemoglobin
    - creatinine
    - blood urea nitrogen
    - bicarbonate
    - calcium ionized
    - partial pressure of carbon dioxide
    - magnesium
    - anion gap
    - phosphorous
    - platelets
  static_list:
    - gender
    - ethnicity
    - age
  drop_first: False                                     # One-hot encoding of categorical static features

  synth_outcome:
    exogeneous_vars:
      - heart rate
      - glucose
      - sodium
    exog_dependency:
      _target_: src.data.mimic.utils.RandomFourierFeaturesFunction
      input_dim: 3
      gamma: 0.005
      scale: 40.0
    exog_weight: 0.9
    endo_dependency:
      _target_: src.data.mimic.utils.DiscretizedRandomGPFunction
      kernels:
        - _target_: sklearn.gaussian_process.kernels.Matern
          length_scale: 25.0
          nu: 2.5
        - _target_: sklearn.gaussian_process.kernels.WhiteKernel
          noise_level: 0.005
    endo_rand_weight: 0.4
    endo_spline_weight: 2.0
    outcome_name: y1

  synth_treatments_list:
    - _target_: src.data.mimic.semi_synthetic_dataset.SyntheticTreatment
      confounding_vars:
        - blood urea nitrogen
        - glucose
        - sodium
      confounder_outcomes:
        - y1
      confounding_dependency:
        _target_: src.data.mimic.utils.RandomFourierFeaturesFunction
        input_dim: 3
        gamma: 0.01
        scale: 30.0
      window: 3
      conf_outcome_weight:  2.5
      conf_vars_weight: 2.5
      bias: 0.0
      full_effect: -1.0
      effect_window: 20
      treatment_name: t1

    - _target_: src.data.mimic.semi_synthetic_dataset.SyntheticTreatment
      confounding_vars:
        - systemic vascular resistance
        - bicarbonate
        - anion gap
      confounder_outcomes:
        - y1
      confounding_dependency:
        _target_: src.data.mimic.utils.RandomFourierFeaturesFunction
        input_dim: 3
        gamma: 0.01
        scale: 30.0
      window: 3
      conf_outcome_weight: 2.0
      conf_vars_weight: 0.25
      bias: 1.0
      full_effect: -0.8
      effect_window: 20
      treatment_name: t2

  treatment_outcomes_influence:                                               # dict with treatment-outcomes influences
    y1:
    - t1
    - t2

exp:
  unscale_rmse: False
  percentage_rmse: False